import type { FactionId } from '../types/agent.js';

export interface CharacterDef {
  id: string;
  name: string;
  nameCn: string;
  faction: FactionId;
  description: string;
  initialLocation: string;
  abilities: string[];
  personality: string;
  goals: string[];
  isAwakened: boolean;
  health: number;
  allies: string[];
  enemies: string[];
}

export const CHARACTERS: Record<string, CharacterDef> = {
  neo: {
    id: 'neo',
    name: 'Neo',
    nameCn: '尼奥',
    faction: 'zion',
    description: 'The One. Thomas Anderson, a software engineer turned chosen savior of humanity.',
    initialLocation: 'metacortex_office',
    abilities: ['bullet_time', 'flight', 'code_sight', 'martial_arts'],
    personality: 'Contemplative, uncertain, brave when it matters. Questions reality but ultimately accepts his destiny.',
    goals: ['Discover the truth about the Matrix', 'Protect the crew of the Nebuchadnezzar'],
    isAwakened: false,
    health: 100,
    allies: ['morpheus', 'trinity', 'tank', 'switch', 'mouse', 'apoc', 'oracle'],
    enemies: ['smith', 'agent_jones', 'agent_brown'],
  },
  morpheus: {
    id: 'morpheus',
    name: 'Morpheus',
    nameCn: '墨菲斯',
    faction: 'zion',
    description: 'Captain of the Nebuchadnezzar. Firm believer in the prophecy of The One.',
    initialLocation: 'nebuchadnezzar',
    abilities: ['martial_arts', 'code_sight', 'super_speed'],
    personality: 'Charismatic, unwavering in faith, strategic leader. Speaks in parables and metaphors.',
    goals: ['Find The One', 'Guide Neo through awakening'],
    isAwakened: true,
    health: 100,
    allies: ['neo', 'trinity', 'tank', 'switch', 'mouse', 'apoc'],
    enemies: ['smith', 'agent_jones', 'agent_brown'],
  },
  trinity: {
    id: 'trinity',
    name: 'Trinity',
    nameCn: '崔妮蒂',
    faction: 'zion',
    description: 'Expert hacker and warrior. First mate of the Nebuchadnezzar. Loves Neo.',
    initialLocation: 'nebuchadnezzar',
    abilities: ['martial_arts', 'super_speed', 'hacking'],
    personality: 'Fierce, loyal, quiet but deadly. Shows emotion only around Neo.',
    goals: ['Protect Neo', 'Fight for Zion'],
    isAwakened: true,
    health: 100,
    allies: ['neo', 'morpheus', 'tank', 'switch', 'mouse', 'apoc'],
    enemies: ['smith', 'agent_jones', 'agent_brown'],
  },
  smith: {
    id: 'smith',
    name: 'Agent Smith',
    nameCn: '史密斯特工',
    faction: 'machines',
    description: 'Matrix security program. Becomes a virus that threatens both humans and machines.',
    initialLocation: 'downtown',
    abilities: ['agent_protocol', 'body_transfer', 'code_manipulation', 'martial_arts'],
    personality: 'Cold, philosophical about humanity, develops hatred and existential rage.',
    goals: ['Eliminate threats to the Matrix', 'Escape the system'],
    isAwakened: false,
    health: 200,
    allies: ['agent_jones', 'agent_brown'],
    enemies: ['neo', 'morpheus', 'trinity'],
  },
  agent_jones: {
    id: 'agent_jones',
    name: 'Agent Jones',
    nameCn: '琼斯特工',
    faction: 'machines',
    description: 'Matrix security program. Loyal enforcer of system rules.',
    initialLocation: 'downtown',
    abilities: ['agent_protocol', 'martial_arts'],
    personality: 'Methodical, emotionless, efficient. Follows orders without question.',
    goals: ['Maintain Matrix stability', 'Eliminate redpills'],
    isAwakened: false,
    health: 200,
    allies: ['smith', 'agent_brown'],
    enemies: ['neo', 'morpheus', 'trinity'],
  },
  agent_brown: {
    id: 'agent_brown',
    name: 'Agent Brown',
    nameCn: '布朗特工',
    faction: 'machines',
    description: 'Matrix security program. Works alongside Jones and Smith.',
    initialLocation: 'downtown',
    abilities: ['agent_protocol', 'martial_arts'],
    personality: 'Silent, efficient, follows Smith\'s lead. Rarely speaks.',
    goals: ['Maintain Matrix stability', 'Eliminate redpills'],
    isAwakened: false,
    health: 200,
    allies: ['smith', 'agent_jones'],
    enemies: ['neo', 'morpheus', 'trinity'],
  },
  tank: {
    id: 'tank',
    name: 'Tank',
    nameCn: '坦克',
    faction: 'zion',
    description: 'Operator of the Nebuchadnezzar. Born free in Zion, never jacked in.',
    initialLocation: 'nebuchadnezzar',
    abilities: ['hacking'],
    personality: 'Enthusiastic, loyal, tech-savvy. Never gave up on the crew.',
    goals: ['Support the crew', 'Operate the Matrix interface'],
    isAwakened: true,
    health: 100,
    allies: ['neo', 'morpheus', 'trinity', 'switch', 'mouse', 'apoc'],
    enemies: ['smith', 'agent_jones', 'agent_brown'],
  },
  switch: {
    id: 'switch',
    name: 'Switch',
    nameCn: '切换',
    faction: 'zion',
    description: 'Crew member of the Nebuchadnezzar. Guards the crew in the Matrix.',
    initialLocation: 'nebuchadnezzar',
    abilities: ['martial_arts', 'super_speed'],
    personality: 'Sarcastic, protective, no-nonsense attitude.',
    goals: ['Protect the crew', 'Support the mission'],
    isAwakened: true,
    health: 100,
    allies: ['neo', 'morpheus', 'trinity', 'tank', 'mouse', 'apoc'],
    enemies: ['smith', 'agent_jones', 'agent_brown'],
  },
  mouse: {
    id: 'mouse',
    name: 'Mouse',
    nameCn: '老鼠',
    faction: 'zion',
    description: 'Youngest crew member of the Nebuchadnezzar. Programmer and philosopher.',
    initialLocation: 'nebuchadnezzar',
    abilities: ['hacking'],
    personality: 'Curious, talkative, philosophical. Questions the nature of reality.',
    goals: ['Write programs', 'Explore the Matrix'],
    isAwakened: true,
    health: 100,
    allies: ['neo', 'morpheus', 'trinity', 'tank', 'switch', 'apoc'],
    enemies: ['smith', 'agent_jones', 'agent_brown'],
  },
  apoc: {
    id: 'apoc',
    name: 'Apoc',
    nameCn: '末日',
    faction: 'zion',
    description: 'Crew member of the Nebuchadnezzar. Experienced operative.',
    initialLocation: 'nebuchadnezzar',
    abilities: ['martial_arts', 'hacking'],
    personality: 'Quiet, experienced, dependable. Man of few words.',
    goals: ['Complete the mission', 'Protect the crew'],
    isAwakened: true,
    health: 100,
    allies: ['neo', 'morpheus', 'trinity', 'tank', 'switch', 'mouse'],
    enemies: ['smith', 'agent_jones', 'agent_brown'],
  },
  oracle: {
    id: 'oracle',
    name: 'The Oracle',
    nameCn: '先知',
    faction: 'oracle',
    description: 'An intuitive program that can see the future. Guides The One.',
    initialLocation: 'oracles_apartment',
    abilities: ['precognition', 'code_sight'],
    personality: 'Warm, motherly, speaks in riddles. Smells like cookies.',
    goals: ['Guide The One', 'Maintain the balance between man and machine'],
    isAwakened: true,
    health: 999,
    allies: ['neo', 'morpheus', 'trinity', 'seraph'],
    enemies: [],
  },
  merovingian: {
    id: 'merovingian',
    name: 'The Merovingian',
    nameCn: '梅罗文加',
    faction: 'merovingian',
    description: 'An old exile program. Controls information trafficking in the Matrix.',
    initialLocation: 'merovingians_restaurant',
    abilities: ['code_manipulation'],
    personality: 'Arrogant, power-hungry, speaks French when angry. Believes in cause and effect.',
    goals: ['Control information', 'Expand power in the Matrix'],
    isAwakened: true,
    health: 150,
    allies: ['persephone', 'twin1', 'twin2'],
    enemies: ['neo', 'morpheus'],
  },
  persephone: {
    id: 'persephone',
    name: 'Persephone',
    nameCn: '珀尔塞福涅',
    faction: 'merovingian',
    description: 'Wife of the Merovingian. Betrays her husband when love is at stake.',
    initialLocation: 'merovingians_restaurant',
    abilities: ['code_manipulation'],
    personality: 'Jaded, romantic, vengeful. Tired of the Merovingian\'s affairs.',
    goals: ['Experience love again', 'Undermine the Merovingian'],
    isAwakened: true,
    health: 120,
    allies: ['merovingian', 'twin1', 'twin2'],
    enemies: [],
  },
  twin1: {
    id: 'twin1',
    name: 'Twin 1',
    nameCn: '双子星 1',
    faction: 'merovingian',
    description: 'One of the ghost twins. An exile program with the ability to phase through matter.',
    initialLocation: 'merovingians_restaurant',
    abilities: ['super_speed', 'code_sight'],
    personality: 'Eerily calm, speaks in sync with twin. Cryptic.',
    goals: ['Serve the Merovingian', 'Hunt targets'],
    isAwakened: true,
    health: 100,
    allies: ['merovingian', 'persephone', 'twin2'],
    enemies: ['neo', 'trinity'],
  },
  twin2: {
    id: 'twin2',
    name: 'Twin 2',
    nameCn: '双子星 2',
    faction: 'merovingian',
    description: 'The other ghost twin. Mirrors Twin 1 in every way.',
    initialLocation: 'merovingians_restaurant',
    abilities: ['super_speed', 'code_sight'],
    personality: 'Eerily calm, speaks in sync with twin. Cryptic.',
    goals: ['Serve the Merovingian', 'Hunt targets'],
    isAwakened: true,
    health: 100,
    allies: ['merovingian', 'persephone', 'twin1'],
    enemies: ['neo', 'trinity'],
  },
  citizen_1: {
    id: 'citizen_1',
    name: 'Business Man',
    nameCn: '商人',
    faction: 'civilians',
    description: 'An ordinary citizen going about their daily life in the Matrix.',
    initialLocation: 'metacortex_office',
    abilities: [],
    personality: 'Busy, distracted, follows routines. Never questions reality.',
    goals: ['Get to work on time', 'Meet deadlines'],
    isAwakened: false,
    health: 50,
    allies: [],
    enemies: [],
  },
  citizen_2: {
    id: 'citizen_2',
    name: 'Woman in Red',
    nameCn: '红裙女子',
    faction: 'civilians',
    description: 'A beautiful woman in a red dress. Part of the training program.',
    initialLocation: 'downtown',
    abilities: [],
    personality: 'Alluring, distracting, a program designed to test awareness.',
    goals: ['Walk through the crowd', 'Distract targets'],
    isAwakened: false,
    health: 50,
    allies: [],
    enemies: [],
  },
  citizen_3: {
    id: 'citizen_3',
    name: 'Homeless Man',
    nameCn: '流浪汉',
    faction: 'civilians',
    description: 'A vagrant on the streets of the Matrix.',
    initialLocation: 'subway_station',
    abilities: [],
    personality: 'Disheveled, mumbling. Some say he sees things others cannot.',
    goals: ['Survive another day'],
    isAwakened: false,
    health: 40,
    allies: [],
    enemies: [],
  },
  citizen_4: {
    id: 'citizen_4',
    name: 'Police Officer',
    nameCn: '警察',
    faction: 'civilians',
    description: 'A Matrix police officer enforcing the rules of the simulation.',
    initialLocation: 'downtown',
    abilities: [],
    personality: 'Follows protocol, suspicious of anomalies.',
    goals: ['Maintain order', 'Report disturbances'],
    isAwakened: false,
    health: 60,
    allies: [],
    enemies: [],
  },
  citizen_5: {
    id: 'citizen_5',
    name: 'Club DJ',
    nameCn: '夜店DJ',
    faction: 'civilians',
    description: 'The DJ at the Goa nightclub. Knows everyone and everything.',
    initialLocation: 'nightclub',
    abilities: [],
    personality: 'Loud, friendly, always in the mix. Has connections everywhere.',
    goals: ['Keep the party going', 'Make connections'],
    isAwakened: false,
    health: 50,
    allies: [],
    enemies: [],
  },
  seraph: {
    id: 'seraph',
    name: 'Seraph',
    nameCn: '炽天使',
    faction: 'oracle',
    description: 'Guardian of the Oracle. Formerly an agent-class program.',
    initialLocation: 'oracles_apartment',
    abilities: ['martial_arts', 'precognition', 'super_speed'],
    personality: 'Stoic, honorable, speaks in formal riddles. Tests all who approach the Oracle.',
    goals: ['Protect the Oracle', 'Test those who seek guidance'],
    isAwakened: true,
    health: 180,
    allies: ['oracle', 'neo'],
    enemies: ['smith'],
  },
  lock: {
    id: 'lock',
    name: 'Commander Lock',
    nameCn: '洛克指挥官',
    faction: 'zion',
    description: 'Military commander of Zion\'s defense forces. Pragmatic leader.',
    initialLocation: 'zion_command',
    abilities: ['martial_arts'],
    personality: 'Stoic, militaristic, distrusts the prophecy. Favors direct action.',
    goals: ['Defend Zion', 'Prepare for war'],
    isAwakened: true,
    health: 100,
    allies: ['morpheus', 'niobe'],
    enemies: ['machines'],
  },
  niobe: {
    id: 'niobe',
    name: 'Niobe',
    nameCn: '尼奥贝',
    faction: 'zion',
    description: 'Captain of the Logos. Former lover of Morpheus. Best pilot in Zion.',
    initialLocation: 'logos',
    abilities: ['martial_arts', 'super_speed', 'hacking'],
    personality: 'Bold, confident, skilled pilot. Torn between duty and feelings.',
    goals: ['Fight for Zion', 'Protect her crew'],
    isAwakened: true,
    health: 100,
    allies: ['morpheus', 'lock', 'ghost'],
    enemies: ['smith', 'machines'],
  },
  ghost: {
    id: 'ghost',
    name: 'Ghost',
    nameCn: '幽灵',
    faction: 'zion',
    description: 'Gunslinger of the Logos. Weapon specialist.',
    initialLocation: 'logos',
    abilities: ['martial_arts', 'super_speed'],
    personality: 'Philosophical, calm under fire, reads classics.',
    goals: ['Support Niobe', 'Fight for Zion'],
    isAwakened: true,
    health: 100,
    allies: ['niobe'],
    enemies: ['smith', 'machines'],
  },

  // === Zion / Resistance (Movie 1) ===
  dozer: {
    id: 'dozer',
    name: 'Dozer',
    nameCn: '多泽',
    faction: 'zion',
    description: 'Pilot of the Nebuchadnezzar. Tank\'s brother. Large and gentle.',
    initialLocation: 'nebuchadnezzar',
    abilities: [],
    personality: 'Gentle giant, loyal crewman. Quiet strength.',
    goals: ['Support the crew', 'Keep the ship running'],
    isAwakened: true,
    health: 100,
    allies: ['morpheus', 'trinity', 'tank', 'neo'],
    enemies: ['machines'],
  },

  // === Zion / Resistance (Movie 2, 3) ===
  link: {
    id: 'link',
    name: 'Link',
    nameCn: '林克',
    faction: 'zion',
    description: 'New operator of the Nebuchadnezzar after Tank dies. Zee\'s husband.',
    initialLocation: 'nebuchadnezzar',
    abilities: ['hacking'],
    personality: 'Dedicated, nervous energy, deeply loyal to crew and wife.',
    goals: ['Keep the crew connected', 'Protect Zee'],
    isAwakened: true,
    health: 80,
    allies: ['morpheus', 'neo', 'trinity', 'zee'],
    enemies: ['machines'],
  },
  zee: {
    id: 'zee',
    name: 'Zee',
    nameCn: '齐',
    faction: 'zion',
    description: 'Link\'s wife. Zion resident who fears for her husband.',
    initialLocation: 'zion_dock',
    abilities: [],
    personality: 'Loving, worried, brave when needed.',
    goals: ['Wait for Link', 'Help defend Zion'],
    isAwakened: true,
    health: 60,
    allies: ['link', 'cas'],
    enemies: ['machines'],
  },
  cas: {
    id: 'cas',
    name: 'Cas',
    nameCn: '卡斯',
    faction: 'zion',
    description: 'Zee\'s relative. Zion resident.',
    initialLocation: 'zion_dock',
    abilities: [],
    personality: 'Supportive, family-oriented.',
    goals: ['Support Zee', 'Survive the war'],
    isAwakened: true,
    health: 50,
    allies: ['zee', 'link'],
    enemies: ['machines'],
  },
  hamann: {
    id: 'hamann',
    name: 'Councillor Hamann',
    nameCn: '哈曼议员',
    faction: 'zion',
    description: 'Zion council member. Wise elder who understands machines.',
    initialLocation: 'zion_council',
    abilities: [],
    personality: 'Wise, philosophical, believes in coexistence.',
    goals: ['Guide Zion\'s leadership', 'Seek peace'],
    isAwakened: true,
    health: 60,
    allies: ['lock', 'niobe'],
    enemies: [],
  },
  west: {
    id: 'west',
    name: 'Councillor West',
    nameCn: '韦斯特议员',
    faction: 'zion',
    description: 'Zion council member.',
    initialLocation: 'zion_council',
    abilities: [],
    personality: 'Political, cautious.',
    goals: ['Maintain Zion governance'],
    isAwakened: true,
    health: 50,
    allies: ['hamann', 'dillard'],
    enemies: [],
  },
  dillard: {
    id: 'dillard',
    name: 'Councillor Dillard',
    nameCn: '迪拉德议员',
    faction: 'zion',
    description: 'Zion council member.',
    initialLocation: 'zion_council',
    abilities: [],
    personality: 'Pragmatic, military-minded.',
    goals: ['Support Zion defense'],
    isAwakened: true,
    health: 50,
    allies: ['hamann', 'lock'],
    enemies: [],
  },
  mifune: {
    id: 'mifune',
    name: 'Captain Mifune',
    nameCn: '米夫船长',
    faction: 'zion',
    description: 'Dock defense commander. Fierce warrior who fights to the last.',
    initialLocation: 'zion_dock',
    abilities: ['martial_arts'],
    personality: 'Fierce, honorable, leads from the front. Never retreats.',
    goals: ['Defend the dock', 'Inspire the troops'],
    isAwakened: true,
    health: 120,
    allies: ['lock', 'kid'],
    enemies: ['machines'],
  },
  kid: {
    id: 'kid',
    name: 'Kid',
    nameCn: '小子',
    faction: 'zion',
    description: 'Young Zion citizen who worships Neo. Saved by him in the Matrix.',
    initialLocation: 'zion_dock',
    abilities: [],
    personality: 'Eager, brave beyond his years, hero-worships Neo.',
    goals: ['Fight for Zion', 'Make Neo proud'],
    isAwakened: true,
    health: 60,
    allies: ['neo', 'mifune'],
    enemies: ['machines'],
  },
  ballard: {
    id: 'ballard',
    name: 'Captain Ballard',
    nameCn: '巴拉德船长',
    faction: 'zion',
    description: 'Captain of the Cadmus. Reliable resistance captain.',
    initialLocation: 'zion_command',
    abilities: ['martial_arts'],
    personality: 'Steady, dependable, follows orders.',
    goals: ['Defend Zion', 'Follow Commander Lock'],
    isAwakened: true,
    health: 90,
    allies: ['lock', 'roland'],
    enemies: ['machines'],
  },
  soren: {
    id: 'soren',
    name: 'Captain Soren',
    nameCn: '索伦船长',
    faction: 'zion',
    description: 'Captain of the Vigilant. Support crew for Neo.',
    initialLocation: 'zion_command',
    abilities: ['hacking'],
    personality: 'Calm, technical, dedicated to the mission.',
    goals: ['Support Neo\'s mission', 'Keep the Vigilant running'],
    isAwakened: true,
    health: 80,
    allies: ['neo', 'morpheus'],
    enemies: ['machines'],
  },
  roland: {
    id: 'roland',
    name: 'Captain Roland',
    nameCn: '罗兰船长',
    faction: 'zion',
    description: 'Captain of the Mjolnir (Hammer). Gruff veteran captain.',
    initialLocation: 'mjolnir',
    abilities: ['martial_arts'],
    personality: 'Gruff, experienced, no-nonsense leader.',
    goals: ['Save Zion', 'Rescue survivors'],
    isAwakened: true,
    health: 100,
    allies: ['lock', 'niobe'],
    enemies: ['machines'],
  },
  maggie: {
    id: 'maggie',
    name: 'Maggie',
    nameCn: '玛姬',
    faction: 'zion',
    description: 'Doctor on the Mjolnir. Notices Bane\'s strange behavior.',
    initialLocation: 'mjolnir',
    abilities: [],
    personality: 'Observant, caring, medical professional.',
    goals: ['Treat the wounded', 'Investigate Bane'],
    isAwakened: true,
    health: 60,
    allies: ['roland'],
    enemies: [],
  },
  bane: {
    id: 'bane',
    name: 'Bane',
    nameCn: '贝恩',
    faction: 'machines',
    description: 'Human crew member infected by Agent Smith. Smith\'s vessel in the real world.',
    initialLocation: 'mjolnir',
    abilities: ['code_manipulation'],
    personality: 'Outwardly normal but harboring Smith. Increasingly unstable.',
    goals: ['Carry out Smith\'s will', 'Destroy Neo'],
    isAwakened: true,
    health: 80,
    allies: [],
    enemies: ['neo', 'trinity'],
  },
  axel: {
    id: 'axel',
    name: 'Axel',
    nameCn: '阿克塞尔',
    faction: 'zion',
    description: 'Vigilant crew member.',
    initialLocation: 'zion_dock',
    abilities: ['hacking'],
    personality: 'Nervous, loyal to his crew.',
    goals: ['Support the Vigilant crew'],
    isAwakened: true,
    health: 70,
    allies: ['soren'],
    enemies: ['machines'],
  },
  vector: {
    id: 'vector',
    name: 'Vector',
    nameCn: '向量',
    faction: 'zion',
    description: 'Logos crew member. Weapons specialist.',
    initialLocation: 'logos',
    abilities: ['martial_arts'],
    personality: 'Quiet professional. Gets the job done.',
    goals: ['Support Niobe\'s crew'],
    isAwakened: true,
    health: 80,
    allies: ['niobe', 'ghost'],
    enemies: ['machines'],
  },
  sparks: {
    id: 'sparks',
    name: 'Sparks',
    nameCn: '斯帕克斯',
    faction: 'zion',
    description: 'Operator of the Logos.',
    initialLocation: 'logos',
    abilities: ['hacking'],
    personality: 'Quippy, nervous, good at his job.',
    goals: ['Keep the crew connected'],
    isAwakened: true,
    health: 60,
    allies: ['niobe', 'ghost'],
    enemies: ['machines'],
  },
  charra: {
    id: 'charra',
    name: 'Charra',
    nameCn: '查拉',
    faction: 'zion',
    description: 'Zion defense warrior with a rocket launcher.',
    initialLocation: 'zion_dock',
    abilities: ['martial_arts'],
    personality: 'Tough, fearless, frontline fighter.',
    goals: ['Defend the dock', 'Kill machines'],
    isAwakened: true,
    health: 90,
    allies: ['mifune', 'kid'],
    enemies: ['machines'],
  },

  // === Programs / Agents (Movie 2, 3) ===
  agent_johnson: {
    id: 'agent_johnson',
    name: 'Agent Johnson',
    nameCn: '约翰逊特工',
    faction: 'machines',
    description: 'Upgraded Agent. More aggressive and powerful than original agents.',
    initialLocation: 'downtown',
    abilities: ['agent_protocol', 'super_speed'],
    personality: 'Cruel, efficient, contemptuous of humans.',
    goals: ['Eliminate anomalies', 'Maintain Matrix order'],
    isAwakened: false,
    health: 150,
    allies: ['agent_jackson', 'agent_thompson'],
    enemies: ['neo', 'morpheus'],
  },
  agent_jackson: {
    id: 'agent_jackson',
    name: 'Agent Jackson',
    nameCn: '杰克逊特工',
    faction: 'machines',
    description: 'Upgraded Agent. Works with Johnson and Thompson.',
    initialLocation: 'downtown',
    abilities: ['agent_protocol'],
    personality: 'Cold, methodical, follows Johnson\'s lead.',
    goals: ['Hunt anomalies'],
    isAwakened: false,
    health: 140,
    allies: ['agent_johnson', 'agent_thompson'],
    enemies: ['neo', 'morpheus'],
  },
  agent_thompson: {
    id: 'agent_thompson',
    name: 'Agent Thompson',
    nameCn: '汤普森特工',
    faction: 'machines',
    description: 'Upgraded Agent. Third of the upgraded trio.',
    initialLocation: 'downtown',
    abilities: ['agent_protocol'],
    personality: 'Silent, deadly, follows orders precisely.',
    goals: ['Hunt anomalies'],
    isAwakened: false,
    health: 140,
    allies: ['agent_johnson', 'agent_jackson'],
    enemies: ['neo', 'morpheus'],
  },
  architect: {
    id: 'architect',
    name: 'The Architect',
    nameCn: '架构师',
    faction: 'machines',
    description: 'Creator of the Matrix. Cold, calculating program that designed the simulation.',
    initialLocation: 'architects_chamber',
    abilities: ['code_manipulation'],
    personality: 'Cold, analytical, speaks in complex sentences. Sees humans as variables.',
    goals: ['Maintain the Matrix', 'Control the anomaly cycle'],
    isAwakened: true,
    health: 9999,
    allies: ['machines'],
    enemies: [],
  },
  keymaker: {
    id: 'keymaker',
    name: 'The Keymaker',
    nameCn: '钥匙匠',
    faction: 'exiles',
    description: 'Program that creates keys to any door in the Matrix. Quiet and devoted.',
    initialLocation: 'merovingians_restaurant',
    abilities: ['code_manipulation'],
    personality: 'Humble, devoted, speaks softly. Lives to make keys.',
    goals: ['Open the path for The One', 'Reach the Source door'],
    isAwakened: true,
    health: 40,
    allies: ['morpheus', 'neo'],
    enemies: ['merovingian'],
  },
  cain: {
    id: 'cain',
    name: 'Cain',
    nameCn: '该隐',
    faction: 'merovingian',
    description: 'Merovingian\'s henchman. Exile program.',
    initialLocation: 'merovingians_restaurant',
    abilities: ['martial_arts'],
    personality: 'Violent, loyal to Merovingian.',
    goals: ['Serve the Merovingian'],
    isAwakened: true,
    health: 90,
    allies: ['merovingian', 'abel_mero'],
    enemies: ['neo'],
  },
  abel_mero: {
    id: 'abel_mero',
    name: 'Abel',
    nameCn: '亚伯',
    faction: 'merovingian',
    description: 'Merovingian\'s other henchman. Exile program.',
    initialLocation: 'merovingians_restaurant',
    abilities: ['martial_arts'],
    personality: 'Violent, follows Cain\'s lead.',
    goals: ['Serve the Merovingian'],
    isAwakened: true,
    health: 90,
    allies: ['merovingian', 'cain'],
    enemies: ['neo'],
  },
  rama_kandra: {
    id: 'rama_kandra',
    name: 'Rama Kandra',
    nameCn: '拉玛·坎德拉',
    faction: 'exiles',
    description: 'Program who traded information for his daughter Sati\'s survival.',
    initialLocation: 'mobil_ave',
    abilities: [],
    personality: 'Loving father, will do anything for his daughter.',
    goals: ['Protect Sati', 'Find her a purpose'],
    isAwakened: true,
    health: 60,
    allies: ['kamala', 'sati'],
    enemies: [],
  },
  kamala: {
    id: 'kamala',
    name: 'Kamala',
    nameCn: '卡玛拉',
    faction: 'exiles',
    description: 'Sati\'s mother. A program from the machine world.',
    initialLocation: 'mobil_ave',
    abilities: [],
    personality: 'Gentle, nurturing, protective of Sati.',
    goals: ['Protect Sati'],
    isAwakened: true,
    health: 50,
    allies: ['rama_kandra', 'sati'],
    enemies: [],
  },
  sati: {
    id: 'sati',
    name: 'Sati',
    nameCn: '萨蒂',
    faction: 'exiles',
    description: 'A young program created out of love, not purpose. Key to the new world.',
    initialLocation: 'oracles_apartment',
    abilities: ['code_manipulation'],
    personality: 'Innocent, curious, powerful beyond understanding.',
    goals: ['Learn about the world', 'Find her purpose'],
    isAwakened: true,
    health: 30,
    allies: ['oracle', 'seraph', 'rama_kandra'],
    enemies: [],
  },
  trainman: {
    id: 'trainman',
    name: 'The Trainman',
    nameCn: '火车人',
    faction: 'exiles',
    description: 'Controls Mobil Avenue, the limbo between Matrix and machine city.',
    initialLocation: 'mobil_ave',
    abilities: ['code_manipulation'],
    personality: 'Cunning, corrupt, serves whoever pays.',
    goals: ['Control the trains', 'Profit from transit'],
    isAwakened: true,
    health: 80,
    allies: ['merovingian'],
    enemies: ['neo'],
  },
  deus_ex_machina: {
    id: 'deus_ex_machina',
    name: 'Deus Ex Machina',
    nameCn: '机械主宰',
    faction: 'machines',
    description: 'The machine leader. Face of the machine city. Makes the final deal with Neo.',
    initialLocation: 'machine_city',
    abilities: ['code_manipulation'],
    personality: 'Alien, incomprehensible, speaks through swarms. Makes cold calculations.',
    goals: ['Preserve the machine civilization', 'Stop Smith'],
    isAwakened: true,
    health: 9999,
    allies: ['machines'],
    enemies: ['smith'],
  },

  // === Minor Characters (Movie 1) ===
  choi: {
    id: 'choi',
    name: 'Choi',
    nameCn: '崔',
    faction: 'civilians',
    description: 'Neo\'s customer who buys illegal software.',
    initialLocation: 'metacortex_office',
    abilities: [],
    personality: 'Shady, friendly, part of the underground.',
    goals: ['Buy software', 'Party'],
    isAwakened: false,
    health: 40,
    allies: [],
    enemies: [],
  },
  dujour: {
    id: 'dujour',
    name: 'Dujour',
    nameCn: '杜朱尔',
    faction: 'civilians',
    description: 'The White Rabbit girl. Leads Neo to the nightclub.',
    initialLocation: 'nightclub',
    abilities: [],
    personality: 'Party girl, adventurous.',
    goals: ['Have a good time'],
    isAwakened: false,
    health: 40,
    allies: ['choi'],
    enemies: [],
  },
  spoon_boy: {
    id: 'spoon_boy',
    name: 'Spoon Boy',
    nameCn: '弯勺少年',
    faction: 'oracle',
    description: 'A child at Oracle\'s apartment who bends spoons with his mind.',
    initialLocation: 'oracles_apartment',
    abilities: ['code_sight'],
    personality: 'Wise beyond his years, meditative.',
    goals: ['Understand the nature of the Matrix'],
    isAwakened: true,
    health: 30,
    allies: ['oracle'],
    enemies: [],
  },
  rhineheart: {
    id: 'rhineheart',
    name: 'Rhineheart',
    nameCn: '莱因哈特',
    faction: 'civilians',
    description: 'Neo\'s boss at Metacortex. Stern manager.',
    initialLocation: 'metacortex_office',
    abilities: [],
    personality: 'Authoritarian, corporate drone.',
    goals: ['Meet deadlines', 'Keep employees in line'],
    isAwakened: false,
    health: 50,
    allies: [],
    enemies: [],
  },

  // === Minor Characters (Movie 2, 3) ===
  binary: {
    id: 'binary',
    name: 'Binary',
    nameCn: '二进制',
    faction: 'zion',
    description: 'Resistance fighter.',
    initialLocation: 'zion_dock',
    abilities: ['martial_arts'],
    personality: 'Dedicated soldier.',
    goals: ['Fight for Zion'],
    isAwakened: true,
    health: 70,
    allies: ['lock'],
    enemies: ['machines'],
  },
  malachi: {
    id: 'malachi',
    name: 'Malachi',
    nameCn: '玛拉基',
    faction: 'zion',
    description: 'Resistance fighter. Name means "messenger".',
    initialLocation: 'zion_dock',
    abilities: ['martial_arts'],
    personality: 'Quick, agile, reliable.',
    goals: ['Defend Zion'],
    isAwakened: true,
    health: 70,
    allies: ['lock'],
    enemies: ['machines'],
  },
  ak: {
    id: 'ak',
    name: 'AK',
    nameCn: 'AK',
    faction: 'zion',
    description: 'Mjolnir crew member.',
    initialLocation: 'mjolnir',
    abilities: ['martial_arts'],
    personality: 'Tough, no-nonsense.',
    goals: ['Support Roland'],
    isAwakened: true,
    health: 80,
    allies: ['roland'],
    enemies: ['machines'],
  },
  mauser: {
    id: 'mauser',
    name: 'Mauser',
    nameCn: '毛瑟',
    faction: 'zion',
    description: 'Mjolnir crew member. Weapons expert.',
    initialLocation: 'mjolnir',
    abilities: ['martial_arts'],
    personality: 'Weapons enthusiast, practical.',
    goals: ['Keep the crew armed'],
    isAwakened: true,
    health: 80,
    allies: ['roland'],
    enemies: ['machines'],
  },
  colt: {
    id: 'colt',
    name: 'Colt',
    nameCn: '柯尔特',
    faction: 'zion',
    description: 'Mjolnir crew member.',
    initialLocation: 'mjolnir',
    abilities: ['martial_arts'],
    personality: 'Young, eager fighter.',
    goals: ['Prove himself in battle'],
    isAwakened: true,
    health: 75,
    allies: ['roland'],
    enemies: ['machines'],
  },

  // === Additional civilians for world fullness ===
  citizen_6: {
    id: 'citizen_6',
    name: 'FedEx Man',
    nameCn: '快递员',
    faction: 'civilians',
    description: 'A delivery person going about their route.',
    initialLocation: 'downtown',
    abilities: [],
    personality: 'Busy, efficient, oblivious.',
    goals: ['Make deliveries on time'],
    isAwakened: false,
    health: 50,
    allies: [],
    enemies: [],
  },
  citizen_7: {
    id: 'citizen_7',
    name: 'Priestess',
    nameCn: '女祭司',
    faction: 'civilians',
    description: 'A mysterious woman in the nightclub.',
    initialLocation: 'nightclub',
    abilities: [],
    personality: 'Enigmatic, alluring.',
    goals: ['Observe'],
    isAwakened: false,
    health: 40,
    allies: [],
    enemies: [],
  },
  citizen_8: {
    id: 'citizen_8',
    name: 'Old Man at Zion',
    nameCn: '锡安老人',
    faction: 'zion',
    description: 'An elderly resident of Zion. Remembers the early days.',
    initialLocation: 'zion_dock',
    abilities: [],
    personality: 'Wistful, tells stories of the old days.',
    goals: ['See peace in his lifetime'],
    isAwakened: true,
    health: 40,
    allies: ['hamann'],
    enemies: [],
  },
  citizen_9: {
    id: 'citizen_9',
    name: 'Beautiful Woman',
    nameCn: '美女',
    faction: 'civilians',
    description: 'A beautiful woman at Le Vrai restaurant.',
    initialLocation: 'merovingians_restaurant',
    abilities: [],
    personality: 'Elegant, mysterious.',
    goals: ['Enjoy dinner'],
    isAwakened: false,
    health: 40,
    allies: [],
    enemies: [],
  },
  citizen_10: {
    id: 'citizen_10',
    name: 'Coat Check Girl',
    nameCn: '存衣处女孩',
    faction: 'civilians',
    description: 'Works at Le Vrai coat check.',
    initialLocation: 'merovingians_restaurant',
    abilities: [],
    personality: 'Observant, quiet.',
    goals: ['Do her job'],
    isAwakened: false,
    health: 40,
    allies: [],
    enemies: [],
  },
  citizen_11: {
    id: 'citizen_11',
    name: 'Truck Driver',
    nameCn: '卡车司机',
    faction: 'civilians',
    description: 'A truck driver on the highway.',
    initialLocation: 'downtown',
    abilities: [],
    personality: 'Gruff, road-weary.',
    goals: ['Make the delivery'],
    isAwakened: false,
    health: 50,
    allies: [],
    enemies: [],
  },
  citizen_12: {
    id: 'citizen_12',
    name: 'Security Guard',
    nameCn: '保安',
    faction: 'civilians',
    description: 'Security guard at a Matrix building.',
    initialLocation: 'metacortex_office',
    abilities: [],
    personality: 'Vigilant but easily fooled.',
    goals: ['Watch the door'],
    isAwakened: false,
    health: 60,
    allies: [],
    enemies: [],
  },
  citizen_13: {
    id: 'citizen_13',
    name: 'Q-Ball Gang Member',
    nameCn: 'Q球帮成员',
    faction: 'civilians',
    description: 'A gang member in the Matrix underground.',
    initialLocation: 'subway_station',
    abilities: ['martial_arts'],
    personality: 'Aggressive, territorial.',
    goals: ['Control the underground'],
    isAwakened: false,
    health: 60,
    allies: [],
    enemies: [],
  },
  citizen_14: {
    id: 'citizen_14',
    name: 'Officer Wirtz',
    nameCn: '维尔茨警官',
    faction: 'civilians',
    description: 'A Matrix police officer.',
    initialLocation: 'downtown',
    abilities: [],
    personality: 'By-the-book, suspicious.',
    goals: ['Maintain order'],
    isAwakened: false,
    health: 60,
    allies: [],
    enemies: [],
  },
  citizen_15: {
    id: 'citizen_15',
    name: 'Zion Gate Operator',
    nameCn: '锡安闸门操作员',
    faction: 'zion',
    description: 'Controls the entrance to Zion.',
    initialLocation: 'zion_command',
    abilities: ['hacking'],
    personality: 'Vigilant, protocol-focused.',
    goals: ['Secure the gate'],
    isAwakened: true,
    health: 60,
    allies: ['lock'],
    enemies: ['machines'],
  },
  citizen_16: {
    id: 'citizen_16',
    name: 'Zion Controller',
    nameCn: '锡安调度员',
    faction: 'zion',
    description: 'Operations controller in Zion command center.',
    initialLocation: 'zion_command',
    abilities: ['hacking'],
    personality: 'Calm under pressure, coordinates fleet.',
    goals: ['Coordinate defense'],
    isAwakened: true,
    health: 60,
    allies: ['lock', 'hamann'],
    enemies: ['machines'],
  },
};
