import { FILM_SCENES, LIFE_ACTIONS, LIFE_DESTINATIONS, LOCATIONS, NEO_ANOMALIES, NEO_CHAPTERS, PHILOSOPHY_NAMES,
  distance, lifeActionPosition, lifeRoomCenter, type AgentState, type SandboxState } from '@auto_matrix/shared';
import './neo-life.css';
import { renderFilmJourney } from './FilmJourneyPanel.js';

const escape = (value: unknown): string => String(value ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]!));
const clock = (time: number): string => `${String(Math.floor(time / 1000)).padStart(2, '0')}:${String(Math.floor(time % 1000 * .06)).padStart(2, '0')}`;
const endings = { peace: '知情选择与停战', reboot: '重载与渐进开放', liberation: '公开真相与共同保护' };
const button = (target: string, label: string, disabled = false, name?: string): string => `<button data-action="life" data-target="${target}" ${name ? `aria-label="${escape(name)}"` : ''} ${disabled ? 'disabled' : ''}>${label}</button>`;

export function renderNeoLife(player: AgentState, sandbox: SandboxState, time: number): string {
  if (sandbox.neoLife?.journey) return renderFilmJourney(player, sandbox);
  const life = sandbox.neoLife!; const chapter = NEO_CHAPTERS[life.chapter]; const hour = time / 1000;
  const anomaly = life.anomaly ? NEO_ANOMALIES.find(a => a.id === life.anomaly!.id) : undefined;
  const nearAnomaly = Boolean(life.anomaly && player.isInMatrix && distance(player.position, life.anomaly.position) < 18);
  const activities = LIFE_ACTIONS.filter(a => !a.location || player.isInMatrix && distance(player.position, lifeActionPosition(a)) < 10);
  const contact = life.chapter === 1 && life.contactSignal;
  const home = player.isInMatrix && distance(player.position, lifeRoomCenter('neo_apartment')!) <= 12;
  return `<div class="neo-life-page">
    <header class="life-masthead"><div><span>THE ANDERSON JOURNAL</span><h3>${life.chapter ? chapter.title : '今天，也有值得生活的事。'}</h3><p>第 ${life.cycle} 轮 · 第 ${life.day} 天 · <span id="life-panel-clock">${clock(time)}</span> · ${escape(LOCATIONS[player.currentLocation]?.nameCn ?? '城市街道')}</p></div><div class="life-cash"><small>现金</small><strong>$${life.money}</strong><span>工作评价 ${life.career}</span></div></header>
    <div class="life-needs">${[['精力', life.energy], ['饱腹', life.satiety], ['社交', life.social], ['朋友关系', life.friends]].map(([name, value]) => `<div><span>${name}<b>${Math.round(Number(value))}</b></span><i><em style="width:${value}%"></em></i></div>`).join('')}</div>
    ${life.cycles.length ? `<details class="life-memory"><summary>上一轮已通关 · ${endings[life.cycles.at(-1)!.ending as keyof typeof endings]} · 展开循环记忆</summary>${life.cycles.map(cycle => `<p>第 ${cycle.cycle} 轮 / ${cycle.days} 天 / ${endings[cycle.ending as keyof typeof endings]}<br>自主 ${cycle.philosophy.agency} · 关怀 ${cycle.philosophy.care} · 信任 ${cycle.philosophy.trust} · ${Object.keys(cycle.choices).length} 次剧情选择</p>`).join('')}</details>` : ''}
    ${anomaly ? `<article class="life-anomaly"><span>有一件事，似乎不太对。</span><h3>${anomaly.title}</h3><p>${anomaly.text}</p><div class="life-buttons">${button('anomaly:ignore', '也许是我太累了', !nearAnomaly)}${button('anomaly:observe', '先记下，不急着解释', !nearAnomaly)}${button('anomaly:test', '花 25 分钟核对', !nearAnomaly)}</div>${!nearAnomaly ? `<small>回到${LOCATIONS[life.anomaly!.location].nameCn}发现它的地方，才能调查。</small>${button('go:anomaly', '返回发现异常的地方 →', Boolean(life.activity))}` : ''}</article>` : ''}
    ${life.chapter ? `<article class="life-story"><div class="life-story-index">01</div><div class="life-story-content"><span class="life-kicker">三部曲电影路线</span><h3>${contact ? life.deferredContact ? '白兔的邀请还在。' : '家里的电脑留下了陌生信号。' : '白兔之后，是整个世界。'}</h3><p>${contact ? '你可以先过完今天，再回公寓核对。电脑没有留下发送者；只有亲自调查，才会知道线索通向哪里。' : '继续 Neo 的调查。来自屏幕、夜店和陌生电话的线索将把你带到 Morpheus 面前；办公室里的一次失手也不会让故事结束。'}</p>${button(contact && !home ? 'go:neo_apartment' : 'film:continue', contact && !home ? '先回公寓 →' : life.deferredContact ? '继续白兔的邀请 →' : '以 Neo 继续追查 →', Boolean(life.activity))}<details><summary>另一条视角：Trinity 的开场逃亡</summary><p>从旅馆序幕开始，之后回到 Neo 的故事。</p>${button('film:start', '游玩 Trinity 序幕 →', Boolean(life.activity) || Boolean(life.deferredContact))}</details><p class="life-footnote">生活记录和物品保留。也可以先过完今天，再开始追查。</p></div></article>` : `<article class="life-daily-intro"><span class="life-kicker">不必急着拯救世界。</span><h3>你先是一个生活在这里的人。</h3><p>08:00–11:00 可以开始上班，班次会经过 7 小时。下班后逛街、吃饭或见朋友，累了就回家睡觉。世界也会在你走动时继续计时。</p><p>异常可能出现在任何一次普通经历里。你可以忽略它，也可以留下证据。${life.evidence.length ? `你已经记下 ${life.evidence.length} 种异样，其中 ${life.clues.length} 种经过核对。` : '今天未必会发生什么，这本身也是生活。'}</p></article>`}
    <div class="life-columns"><section><h4>此刻，可以做什么</h4>${life.appointment ? `<p class="life-appointment">已约 Choi · 第 ${life.appointment.day} 天 19:00 · 咖啡馆（18:30–20:30 可赴约）</p>` : ''}<div class="life-actions">${activities.map(action => {
      const reason = life.activity ? '活动进行中' : action.once && life.done[action.id] === life.day ? '今天已完成' : action.window && hour < action.window[0] ? '还未开放' : action.window && hour >= action.window[1] ? '今天已结束' : life.money < action.cost ? '现金不足' : action.id === 'meet' && life.appointment?.day !== life.day ? '需要先预约' : action.id === 'work' && life.energy < 18 ? '需要休息' : '';
      return `<article><div><strong>${action.name}</strong><p>${action.description}</p></div>${button(action.id, reason || '开始 →', Boolean(reason), action.name)}</article>`;
    }).join('')}</div><p class="life-footnote">可以步行探索，也可以安排通勤。活动完成前离开 3 米会中断，不扣费用。</p></section>
    <section><h4>今天想去哪里</h4><div class="life-places">${LIFE_DESTINATIONS.map(id => button(`go:${id}`, `${LOCATIONS[id].nameCn}<span>${player.currentLocation === id ? '附近' : '安排通勤 ↗'}</span>`, Boolean(life.activity))).join('')}${player.isAwakened ? button('go:nebuchadnezzar', '返回飞船<span>接线员路线 ↗</span>', Boolean(life.activity)) : ''}</div><p class="life-footnote">公共交通 $2 / 10–40 分钟。现金不足时步行。能力与剧情目的地随经历开放。</p></section></div>
    <section class="life-philosophy"><h4>你怎样理解这个世界</h4><div>${Object.entries(PHILOSOPHY_NAMES).map(([axis, name]) => `<article><span>${name}</span><b>${life.philosophy[axis as keyof typeof life.philosophy]}</b><p>${axis === 'agency' ? '核对证据，拒绝让预言代替判断。' : axis === 'care' ? '把具体的人与程序视为目的。' : '在不确定中，与他人共同承担。'}</p></article>`).join('')}</div><p class="life-footnote">记录你的实践，没有“哲学答对率”。承诺会改变补给、关系和最终可提出的协议。</p></section>
    <details class="life-roadmap"><summary>三部曲旅程 · ${FILM_SCENES.length} 段电影事件</summary>${[1, 2, 3].map(film => `<div><h4>${['黑客帝国 · 选择真实', '重装上阵 · 选择的原因', '矩阵革命 · 共存的可能'][film - 1]}</h4>${FILM_SCENES.filter(c => c.film === film).map(c => `<span>${c.title}</span>`).join('')}</div>`).join('')}</details>
    <section class="life-journal"><h4>生活留下的痕迹</h4>${life.journal.slice(0, 14).map(entry => `<article><time>DAY ${entry.day}<br>${clock(entry.time)}</time><div><strong>${escape(entry.title)}</strong><p>${escape(entry.text)}</p></div></article>`).join('')}</section>
  </div>`;
}
